### ISSUE TITLE
Get MAC address of devices in scan

### ISSUE THREAD

**Issue by teknetia** [jas-/node-libnmap#10]
I am aware that getting the MAC address of the device on the network requires elevated privileges but it is something I need so I have been investigating how to get this to trigger correctly. Is there a way to get the MAC address for each device and somehow trigger this elevated privilege mode?

**Comment by lutzbickhardt** [comment]
you need to execute as root
but then a different nmap output requires a modification of libnmap. if you want I can mail the solution (lutz AT bickhardt POINT fr)

**Comment by jas-** [comment]
Please refer to my comment in [issue #3](https://github.com/jas-/node-libnmap/issues/3#issuecomment-60752218).

Privileged scanning with this tool is not supported but it can be accomplished.
