### ISSUE TITLE
.128, .64, ... not included ?

### ISSUE THREAD

**Issue by lutzbickhardt** [jas-/node-libnmap#11]
my solution in tools.calculate:
      for (var i = start; i < end; i += split) {
        val= i + split - 1;
        str = octetsStart[0] + '.' + octetsStart[1] + '.' + octetsStart[2] + '.' + i + '-' +
          //((i + (split - 1) > 256) ? (i + (split - 1)) : (i + (split - 1) -1));
          (val == 256 ? val -1 : val); 
        results.push(str);
      }

**Comment by jas-** [comment]
Can you create a `PR` for this?

**Comment by lutzbickhardt** [comment]
sure, over the weekend!


it will also contain the sudo version yielding MAC and other stuff.

I am afraid that much of the code added will look like FORTRAN, though.

Also I had to introduce report["192.168.0.12"] instead of report[0].


Modify as you deem fit (actually I would like to see how it is coded "properly").


Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Jason Gerfen <notifications@github.com>
Envoyé : mercredi 15 juillet 2015 19:19
À : jas-/node-libnmap
Cc : Bickhardt, Lutz
Objet : Re: [node-libnmap] .128, .64, ... not included ? (#11)


Can you create a PR for this?

-

**Comment by jas-** [comment]
@lutzbickhardt It really should do calculations similar to those shown in the [`tools.range()`](https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L426-L452) function to be account for addressing such as `192.168.1-255`

**Comment by lutzbickhardt** [comment]
?no worries, that part is not FORTRAN


Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Jason Gerfen <notifications@github.com>
Envoyé : jeudi 16 juillet 2015 19:10
À : jas-/node-libnmap
Cc : Bickhardt, Lutz
Objet : Re: [node-libnmap] .128, .64, ... not included ? (#11)


@lutzbickhardt<https://github.com/lutzbickhardt> It really should do calculations similar to those shown in the tools.range()<https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L426-L452> function to be account for addressing such as 192.168.1-255

-

**Comment by lutzbickhardt** [comment]
Hi Jason,


did the pull request. This was my first ever, so I hope it is what you expected.

All the other changes, I will eventually put in a wrapper around libnmap, that will keep things cleaner.


I saw that in your example .128, .64 were also missing. Did I really spot an error or was that intentional?


Cordialement

--------------------------
Lutz BICKHARDT
lutz@bickhardt.fr

NEW COORDINATES !!!
(privat) Graumannsweg 42, D-22087 Hamburg, Germany
(Büro)  Borselstr. 3 - 7 (im Hof), D-22765 Hamburg, Germany

SKYPE: bickhardt

+49 172 3846086 (deutsches Handy / German cell phone)
+49 40 22758122 (privat Hamburg)
+49 40 39190921 (Büro Hamburg)
+33 6 18386906 (portable francais/ French cell phone)
________________________________
De : Jason Gerfen <notifications@github.com>
Envoyé : jeudi 16 juillet 2015 19:10
À : jas-/node-libnmap
Cc : Bickhardt, Lutz
Objet : Re: [node-libnmap] .128, .64, ... not included ? (#11)


@lutzbickhardt<https://github.com/lutzbickhardt> It really should do calculations similar to those shown in the tools.range()<https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L426-L452> function to be account for addressing such as 192.168.1-255

-

**Comment by jas-** [comment]
@lutzbickhardt This really needs to use the [tools.range()](https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L426-L452) function by sending in the local IP per adapter as well as the subnet provided from [os.networkInterfaces()](https://nodejs.org/api/os.html#os_os_networkinterfaces).

**Comment by jas-** [comment]
Version update to `v0.2.2` resolves this. Thanks!
