### ISSUE TITLE
Suggest to install nmap with homebrew

### ISSUE THREAD

**Issue by mrzmyr** [jas-/node-libnmap#14]
May you should suggest to install the binary `nmap` on other platforms than *nix.

OSX: `brew install nmap`

Source: http://superuser.com/a/863974/69046

**Comment by jas-** [comment]
Forgive me but this is a confusing statement. The function [setup.check()](https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L182-L195) actually does what you are asking in regards to informing the implementer that the `nmap` binary is missing. Did it not do that on `OSX`?

**Comment by mrzmyr** [comment]
Yes, sure it does. It could be helpful to have a simple reference in the `README.md` how to install the `nmap` binary. ([Maybe here](https://github.com/jas-/node-libnmap#nmap-binary))

**Comment by jas-** [comment]
Thanks for the suggestion but installation of the nmap binary is better left to the documentation for nmap as your systems package management is outside the scope of this tool.
