### ISSUE TITLE
Make timing template configurable

### ISSUE THREAD

**Issue by mrzmyr** [jas-/node-libnmap#15]
As currently the [`-T4`](https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L78) limits the timing template, it would be great to make it configurable. 

In case PRs are welcome, let me know which API design you would use.

**Comment by jas-** [comment]
Please review the `contributing` section within the [README.md](https://github.com/jas-/node-libnmap/blob/master/README.md).

**Comment by jas-** [comment]
I am going to go ahead and close this as it is being addressed in branch [v0.2.0](https://github.com/jas-/node-libnmap/blob/v0.2.0/lib/node-libnmap.js#L38-L42)
