### ISSUE TITLE
Discuss: Use xml as output instead of cli output parsing

### ISSUE THREAD

**Issue by mrzmyr** [jas-/node-libnmap#16]
I came along with a few problems with the [`report`](https://github.com/jas-/node-libnmap/blob/master/lib/node-libnmap.js#L539) function. The parser didn't work well when passing in some different flag. So I decided to implement in [my fork](https://github.com/mrzmyr/node-libnmap/commit/21cbec2aece103df5f3aeec596bc9c50b85af524) a version where the XML output (`-oX -`) is used. This has the benefit that you have a way better control about the data you are getting out of the reports (basically all data which comes from `nmap`).

As I saw that you commented some better practices in my code, I thought about discussing if you would like to have this in your module as well and, if you do so, to discuss about a short feature list (as you already commented in the fork).

What do you think?

**Comment by jas-** [comment]
It was designed to capture only a few of the available options and return a `json` object. Perhaps as you mentioned it would be better to simply return an XML option and use the [xml2json](https://www.npmjs.com/package/xml2json) for the returned report. I still feel returning the `json` object type should be the default value but as I mentioned pull requests are welcome.

**Comment by mrzmyr** [comment]
Its actually not about returning a XML object. Its more about using the XML output and [bring it into the JSON format](https://github.com/mrzmyr/node-libnmap/blob/21cbec2aece103df5f3aeec596bc9c50b85af524/lib/node-libnmap.js#L103).

**Comment by jas-** [comment]
Well I think it is a worth while endeavor.

**Comment by mrzmyr** [comment]
I updated the branch now: https://github.com/mrzmyr/node-libnmap/tree/feature/replace-cli-parser-with-xml-parser

Before applying, I would write a simple and easy migration. How to use the ["old"](https://github.com/jas-/node-libnmap#output-2) output with the [new one](https://github.com/mrzmyr/node-libnmap/blob/feature/replace-cli-parser-with-xml-parser/README.md#output-2).

**Comment by jas-** [comment]
You can remove the linking in the category title. Not really needed for implementers. I don't think we would need the 'easy migration' docs either as we can simply state that 'updating to v2.x' is a breaking change release.

**Comment by mrzmyr** [comment]
What do you mean by the 'linking in the category title' ?

**Comment by jas-** [comment]
Oh, sure. In your [updated readme](https://github.com/mrzmyr/node-libnmap/blob/feature/replace-cli-parser-with-xml-parser/README.md#output-2) you provide two separate links; one under 'Flatten' which links to the function within the source code & the second provides a link to the nmap output documentation.

I think both of those are un-necessary. Are you familiar with the [semantic versioning](http://semver.org/)?

**Comment by mrzmyr** [comment]
3162a51583632b317645d11840f5a1c14353d8a1, done.
Yes, I know semantic versioning. Don't you want to merge and version it ?

**Comment by jas-** [comment]
Thanks, this has landed in [bcc55ea](https://github.com/jas-/node-libnmap/commit/bcc55ea531080e3c1a474ed038bf96c9a1e3752a)
