### ISSUE TITLE
Bring the $ dollar back

### ISSUE THREAD

**Issue by mrzmyr** [jas-/node-libnmap#21]
As I just saw, the $ holds [important information](https://github.com/jas-/node-libnmap#output-2), like the port information of each item. We should bring them back though. 

That means to just simply revert the commit ca91cae26bfbfc08ee2e076ce75478f8cbb5336b

**Comment by jas-** [comment]
Sure, it got committed on accident anyways. I will manually remote it. Is there a way to name it based on the schema? Adding conditionals during the conversion seems clunky.

**Comment by jas-** [comment]
Landed in [ffc604b822](https://github.com/jas-/node-libnmap/commit/ffc604b822e931eb06269ce05dbc1d9e1e261a3e)
