### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by nmors** [jas-/node-libnmap#22]
Somewhere, the async done() is being called multiple times. Needs better handling.

To produce this error, it was very simple. The scan target is 127.0.0.1, scanning ports 80, 443, 22

I ONLY get the error, when I disconnect from my WiFi network. Very strange.

/myproject/node_modules/node-libnmap/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at /myproject/node_modules/node-libnmap/node_modules/async/lib/async.js:43:36
    at /myproject/node_modules/node-libnmap/node_modules/async/lib/async.js:694:17
    at /myproject/node_modules/node-libnmap/node_modules/async/lib/async.js:173:37
    at Object.reporting.reports (/myproject/node_modules/node-libnmap/lib/node-libnmap.js:138:9)
    at Socket.errbytesend (/myproject/node_modules/node-libnmap/lib/node-libnmap.js:227:25)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by nmors** [comment]
I'm running on ubuntu 14.04 64 bit desktop by the way, using node v0.12.0

**Comment by jas-** [comment]
Do you receive problems when you run 'npm test'?

**Comment by nmors** [comment]
Yep:

nathan@mynode:/myproject/node_modules/aleron_scannor/node_modules/node-libnmap$ npm test

> node-libnmap@0.2.9 test /myproject/node_modules/node-libnmap
> mocha -R spec



  nmap
    discovery method
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range

  nmap
    scan method
      ✓ default (2239ms)
      2) xml report


  6 passing (4s)
  2 failing

  1) nmap discovery method validate report:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) nmap scan method xml report:
     Uncaught Error: Callback was already called.
      at node_modules/async/lib/async.js:43:36
      at node_modules/async/lib/async.js:694:17
      at node_modules/async/lib/async.js:173:37
      at Object.reporting.reports (lib/node-libnmap.js:138:9)
      at Socket.bytesend (lib/node-libnmap.js:236:25)
      at _stream_readable.js:908:16



npm ERR! Test failed.  See above for more details.


BUT,

nmap binary is installed. I can run the nmap command fine from a bash shell, the version I have installed is 6.40, which also is the same as is coming back inside the report when I use the module

the node module works fine normally, apart from in the conditions I stated in the OP, I have done full network scans using CIDR notations and also arrays of hosts.

**Comment by nmors** [comment]
Are you able to replicate the issue using my configuration?

I have compared the two raw commands (without using node, but simply nmap from the shell, using the exact same commands which the lib executes) 
 - 1st test is whilst connected to a network, and 2nd, not connected to any network. The difference is very  interesting. 2nd output is complaining about no DNS server configured: 

"mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers" 

*** Test outputs:

** Connected to WLAN
$ nmap  --host-timeout=100 -oX - -T4 -p80,22,443 127.0.0.1
<?xml version="1.0"?>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>

<nmaprun scanner="nmap" args="nmap -&#45;host-timeout=100 -oX - -T4 -p80,22,443 127.0.0.1" start="1442835959" startstr="Mon Sep 21 21:45:59 2015" version="6.40" xmloutputversion="1.04">
<scaninfo type="connect" protocol="tcp" numservices="3" services="22,80,443"/>
<verbose level="0"/>
<debugging level="0"/>
<host starttime="1442835959" endtime="1442835959"><status state="up" reason="syn-ack" reason_ttl="0"/>
<address addr="127.0.0.1" addrtype="ipv4"/>
<hostnames>
<hostname name="localhost" type="PTR"/>
</hostnames>
<ports><port protocol="tcp" portid="22"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="ssh" method="table" conf="3"/></port>
<port protocol="tcp" portid="80"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="http" method="table" conf="3"/></port>
<port protocol="tcp" portid="443"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="https" method="table" conf="3"/></port>
</ports>
<times srtt="31" rttvar="1600" to="100000"/>
</host>
<runstats><finished time="1442835959" timestr="Mon Sep 21 21:45:59 2015" elapsed="0.03" summary="Nmap done at Mon Sep 21 21:45:59 2015; 1 IP address (1 host up) scanned in 0.03 seconds" exit="success"/><hosts up="1" down="0" total="1"/>
</runstats>
</nmaprun>


** Disconnected from WLAN
$ nmap  --host-timeout=100 -oX - -T4 -p80,22,443 127.0.0.1
<?xml version="1.0"?>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>

<nmaprun scanner="nmap" args="nmap -&#45;host-timeout=100 -oX - -T4 -p80,22,443 127.0.0.1" start="1442835981" startstr="Mon Sep 21 21:46:21 2015" version="6.40" xmloutputversion="1.04">
<scaninfo type="connect" protocol="tcp" numservices="3" services="22,80,443"/>
<verbose level="0"/>
<debugging level="0"/>
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
<host starttime="1442835981" endtime="1442835981"><status state="up" reason="syn-ack" reason_ttl="0"/>
<address addr="127.0.0.1" addrtype="ipv4"/>
<hostnames>
<hostname name="localhost" type="PTR"/>
</hostnames>
<ports><port protocol="tcp" portid="22"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="ssh" method="table" conf="3"/></port>
<port protocol="tcp" portid="80"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="http" method="table" conf="3"/></port>
<port protocol="tcp" portid="443"><state state="open" reason="syn-ack" reason_ttl="0"/><service name="https" method="table" conf="3"/></port>
</ports>
<times srtt="32" rttvar="1600" to="100000"/>
</host>
<runstats><finished time="1442835981" timestr="Mon Sep 21 21:46:21 2015" elapsed="0.02" summary="Nmap done at Mon Sep 21 21:46:21 2015; 1 IP address (1 host up) scanned in 0.02 seconds" exit="success"/><hosts up="1" down="0" total="1"/>
</runstats>
</nmaprun>

**Comment by jas-** [comment]
Well that is a bug, better error handling. Thanks for reporting this.

**Comment by nmors** [comment]
No problem. Thanks for providing the great node module. Glad to be able to help

**Comment by jas-** [comment]
Your the first to try and scan something without an actual connection however

**Comment by jas-** [comment]
@nmors Can you try branch `v0.2.10`?

**Comment by ckiely91** [comment]
@jas-, I receive get this same problem when running an nmap scan with the '-sn' flag enabled.

```javascript
var initialPingScanOpts = {
    verbose: true,
    flags: ['-sn'],
    range: ['192.168.1.1/24']
};

nmap.scan(initialPingScanOpts, function(err, result) {
    if (err) {
        throw new Error(err);
    } else {
        console.log(result);
    }
});
```

I tried implementing your v0.2.10 fix but that did not help.

**Comment by ckiely91** [comment]
Here's the error I received:

```
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.1-16
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.17-32
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.33-48
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.49-64
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.65-80
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.81-96
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.97-112
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.113-128
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.129-144
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.145-160
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.161-176
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.177-192
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.193-208
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.209-224
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.225-240
Running: nmap  --host-timeout=120 -oX - -T4 -sn -p1-1024 192.168.1.241-255
C:\project\node_modules\node-libnmap\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at C:\project\node_modules\node-libnmap\node_modules\async\lib\async.js:43:36
    at C:\project\node_modules\node-libnmap\node_modules\async\lib\async.js:694:17
    at C:\project\node_modules\node-libnmap\node_modules\async\lib\async.js:173:37
    at Object.reporting.reports (C:\project\node_modules\node-libnmap\lib\node-libnmap.js:138:9)
    at Socket.errbytesend (C:\project\node_modules\node-libnmap\lib\node-libnmap.js:227:32)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by nmors** [comment]
I'm still getting the same issue on the 0.2.10 branch: (With WiFi Off)

    Running: nmap  --host-timeout=100 -oX - -T4 -p80,22,443 127.0.0.1

    /myproject/node_modules/node-libnmap/node_modules/async/lib/async.js:43
                if (fn === null) throw new Error("Callback was already called.");
                                       ^
    Error: Callback was already called.
        at /var/www/sareporting/sa-server/node_modules/aleron_scannor/node_modules/node-libnmap/node_modules/async/lib/async.js:43:36
        at /var/www/sareporting/sa-server/node_modules/aleron_scannor/node_modules/node-libnmap/node_modules/async/lib/async.js:694:17
        at /var/www/sareporting/sa-server/node_modules/aleron_scannor/node_modules/node-libnmap/node_modules/async/lib/async.js:173:37
        at Object.reporting.reports (/var/www/sareporting/sa-server/node_modules/aleron_scannor/node_modules/node-libnmap/lib/node-libnmap.js:138:9)
        at Socket.errbytesend (/var/www/sareporting/sa-server/node_modules/aleron_scannor/node_modules/node-libnmap/lib/node-libnmap.js:227:32)
        at Socket.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)



With WiFi on, it's working, but npm test still fails either way:


With WiFi On:

> $ npm test

    ...

    6 passing (3s)
    2 failing

    1) nmap discovery method validate report:
       Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    

    2) nmap scan method xml report:
       Uncaught Error: Callback was already called.
        at node_modules/async/lib/async.js:43:36
        at node_modules/async/lib/async.js:694:17
        at node_modules/async/lib/async.js:173:37
        at Object.reporting.reports (lib/node-libnmap.js:138:9)
        at Socket.bytesend (lib/node-libnmap.js:236:32)
        at _stream_readable.js:908:16





With WiFi Off:

> $ npm test

    ...

    7 passing (82ms)
    1 failing

    1) nmap scan method default:
       Uncaught Error: Callback was already called.
        at node_modules/async/lib/async.js:43:36
        at node_modules/async/lib/async.js:694:17
        at node_modules/async/lib/async.js:173:37
        at Object.reporting.reports (lib/node-libnmap.js:138:9)
        at Socket.errbytesend (lib/node-libnmap.js:227:32)
        at _stream_readable.js:908:16

**Comment by jas-** [comment]
@ckiely91 set the ports option to null
```javascript
var opts = {
  /* ... */
  ports: null,
}
```

**Comment by jas-** [comment]
@nmors Can you try commit 79fd31d which just landed in `v0.2.10`?

**Comment by nmors** [comment]
The 2nd commit fixed it for me!

Thanks

**Comment by jas-** [comment]
Good to hear, thanks for reporting this.

**Comment by ckiely91** [comment]
@jas- Thanks for your help!

**Comment by jas-** [comment]
@ckiely91 no worries, next revision will provide better error handling regarding these types of issues

**Comment by Kikobeats** [comment]
same error here running test (wifi is on):

```bash
npm test

> node-libnmap@0.2.10 test /Users/josefranciscoverdugambin/Downloads/node-libnmap
> mocha -R spec



  nmap
    discovery method
      1) validate report
      ✓ validate report (57ms)
    nmap
    nmap
      error handling
        scan method
          ✓ default (580ms)
          ✓ xml report
          ✓ invalid host range (host)
          ✓ invalid host range (range)
          ✓ invalid host range (CIDR)
          ✓ invalid port range

  7 passing (870ms)
  1 failing

  1) nmap discovery method validate report:
     Uncaught Error: Callback was already called.
      at node_modules/async/lib/async.js:43:36
      at node_modules/async/lib/async.js:694:17
      at node_modules/async/lib/async.js:173:37
      at Object.reporting.reports (lib/node-libnmap.js:138:16)
      at Socket.errbytesend (lib/node-libnmap.js:227:32)
      at _stream_readable.js:908:16



npm ERR! Test failed.  See above for more details.
```

**Comment by jas-** [comment]
@Kikobeats Please open a new issue. Thanks.

**Comment by alundiak** [comment]
@jas- 
>  incompatible with the -sn flag

And yes indeed, for me. Now, 2018 year :) using nodescan v0.7.1
I use nmap 7.60
