### ISSUE TITLE
Error: Error: Supplied path for nmap binary is invalid

### ISSUE THREAD

**Issue by lrengunst** [jas-/node-libnmap#28]
```javascript
var nmap = require('libnmap');
var fs = require('fs');
var path = require("path");
var pathScan = './scans/';
var opts = {
      nmap: "/home/ubuntu/workspace/nmap/nmap",
      range: ['scanme.nmap.org'],
      ports: '21,22,80,443'
    };
    
    console.log("nmap file on",opts.nmap);
    
nmap.scan(opts, function(err, report) {
      if (err) console.log(err);
      for (var item in report) {
            for (var host in report[item].host) {
            var data = JSON.stringify(report[item].host[host]), filename = item;
                  fs.writeFile(pathScan+filename+'.json', data, function(error) {
                        if (error) console.log(error);
                        console.log('Wrote report for '+filename);
                  });
            }
      }
});
```
=======================================================================
r********:~/workspace (master) $ node server
nmap file on /home/ubuntu/workspace/nmap/nmap
[ [Error: Supplied path for nmap binary is invalid] ]

**Comment by jas-** [comment]
I am not able to decipher this use case. Could you please reformat the code and exception blocks using the markdown formatting syntax?

**Comment by lrengunst** [comment]
I've put on a par with the main module and assigned to it understand address located in / home / ubuntu / workspace / nmap / nmap but it does not work
nmap: path.join(__dirname,'/nmap/nmap') => /home/ubuntu/workspace/nmap/nmap

**Comment by jas-** [comment]
I think you should reconsider your `opts` object.

```javascript
var opts = {
  range: ['scanme.nmap.org'],
  ports: '21,22,80,443'
};
```

No need to specify the full path; the `hasbin` module will take care of the binary location and as long as the `nmap` binary exists in the `PATH` or `%SYSTEM%` you should be good to go.

**Comment by lrengunst** [comment]
ordinary users can not install new nmap so used to make the lib .
not custom paths then how can run on the host node cloud ?

**Comment by jas-** [comment]
As long as the nmap binary exists in the system path (please look that up) then this tool will find and use the nmap binary.

**Comment by jas-** [comment]
I am closing this issue. nmap installation is outside the scope of support and considered an edge case implementation issue.
