### ISSUE TITLE
Can node-libnmap be used on windows?

### ISSUE THREAD

**Issue by mattwhetton** [jas-/node-libnmap#32]
Hi,

Can this library be used on windows machines?

I've got the windows version of nmap installed, but I just get an error saying supplied path for nmap binary is invalid.

I've tried setting the nmap option to the installed nmap exe but that gives the same error.

Any pointers?

Matt

**Comment by jas-** [comment]
Have you tried searching the `closed` [issues](https://github.com/jas-/node-libnmap/issues/19)?
