### ISSUE TITLE
Adapter function does not get IPv4 addresses from network interfaces

### ISSUE THREAD

**Issue by cscholze** [jas-/node-libnmap#33]
The adapters function only grabs the first object from adapters[iface] returned from os.NetworkInterfaces().  This can results in skipping network interface IPv4 addresses, resulting in discovering zero hosts on networks that don't use IPv6, even if the interface is assigned an IPv6 address.

**Comment by jas-** [comment]
This should be resolved with `v0.2.28` which is now published on `npm`

**Comment by cscholze** [comment]
I'm going to give that a run now...I've been using a forked version.

**Comment by jas-** [comment]
Does `-PR` work for IPv4 addresses? According to the `nmap` [docs](https://nmap.org/book/man-host-discovery.html) for IPv6 addresses;

> For IPv6 (-6 option), -PR uses ICMPv6 Neighbor Discovery instead of ARP. Neighbor Discovery, defined in RFC 4861, can be seen as the IPv6 equivalent of ARP.

This sounds like a separate issue so a new one would be helpful to keep it easy to maintain.

**Comment by cscholze** [comment]
i'm going to close this and open a new one
