### ISSUE TITLE
IPv4 discovery in blocks of 16

### ISSUE THREAD

**Issue by cscholze** [jas-/node-libnmap#34]
Why break IPv4 host address space into blocks of 16 during the discovery scan?  The JSON output returns results for addresses in blocks of 16.  Why isn't the output one object full of hosts in the scanned range?

**Comment by jas-** [comment]
That block of 16 depends on the number of CPU's returned by the OS.

**Comment by cscholze** [comment]
Is that to increase the nmap scan speed by breaking it into blocks for each processor to use?  I have a quad core and its doing blocks of 16.  Doesn't nmap already manage that?

**Comment by jas-** [comment]
nmap can and does implement multiple threads; this tool increases this by splitting the specified CIDR, range etc. into smaller blocks based on the CPU count and the `threshold` option. In many cases the speed of the scan (provided the host response times are good) is improved.

**Comment by cscholze** [comment]
Awesome, thanks!!
