### ISSUE TITLE
IPv4 not discovering any 'up' hosts

### ISSUE THREAD

**Issue by cscholze** [jas-/node-libnmap#36]
When using discover for IPv4 addresses, the Discover function does not detect any 'up' hosts.  I am able to retrieve 'up' hosts by modifying the default flags and disabling the ARP scan.  Possible fix could be to only use ARP scanning for IPv6 addresses?

**Comment by jas-** [comment]
Can you confirm it works for discovery of IPv6 hosts and not IPv4 hosts?

**Comment by cscholze** [comment]
I'm not sure how I could, since my local network is on a router that uses IPv4 addressing...I'll do some testing and let ya know. May be able to reconfig the router to use IPv6.  I'll get back with my results.

**Comment by jas-** [comment]
The results for a discovery should provide the original scan flags used. If a -6 is in the command string and there are hosts showing 'up' then it is indeed working for IPv6 hosts (provided those results are accurate for your network).

**Comment by jas-** [comment]
@cscholze Since this is nearing a year and I have not seen any additional correspondence I am marking this as resolved. If you experience issues don't hesitate to open a new issue.
