### ISSUE TITLE
host discovery

### ISSUE THREAD

**Issue by tinnocente** [jas-/node-libnmap#39]
Hello,  nice interface to nmap .

I'm wondering what the best way to do host discovery is?  I don't need OS detection or port service detection.  Shown below is (kind of) quick but I think it's scanning ports.  Is there a better way?

nmap.scan( { range : [ "192.168.1.1-25" ], flags : [ '-PR' ]  }, function(err, report) { }

Thanks

**Comment by jas-** [comment]
The examples folder as well as the readme document describe the discovery method available with this module
