### ISSUE TITLE
New Version Error

### ISSUE THREAD

**Issue by thxmike** [jas-/node-libnmap#40]
Something has changed with the new release of libnmap. I am using version 0.2.32 and nmap version 7.01. There error is reported below. Looking at the source in libnmap.js, 
There appears to be is an xml string returned from the reports function and it expects an array. 
Not sure what changed. Let me know if additional information is needed.

``` javascript
D:\blahblahblah\node_modules\libnmap\lib\libnmap.js
:132
                var xml = report.join('');
                                 ^

TypeError: report.join is not a function
    at Object.reporting.reports (D:\blahblahblah\Node Collector\no
de_modules\libnmap\lib\libnmap.js:132:34)
    at exe (D:\blahblahblah\node_modules\libnmap\li
b\libnmap.js:248:50)
    at ChildProcess.exithandler (child_process.js:214:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

After some debugging, it appears that the following error is being swallowed:

``` javascript
{ Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:265:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:542:20)
  cmd: 'nmap  --host-timeout=120s -T4 -O -oX - -p1-1024 192.168.41.65-128' }
```

It appears to be related to the following issue with child_process
http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

**Comment by thxmike** [comment]
I changed the following lines to correct the problem.
#253 execute = proc(cmd, function exe(err, stdout, stderr) {
to this: execute = proc(cmd, **{maxBuffer: 1024 * 500}**, function exe(err, stdout, stderr) {

Making the maxBuffer a configurable item in the nmap options may be desirable for a final solution

In addition, around line number #135 some defensive programing may be in order:
#135 var xml = report.join('');

To maybe something like this:
if(Array.isArray(report)){
                	var xml = report.join('');
		}else{
			throw report //maybe this
			var xml = '' //maybe this
		}

Or maybe changing:
#132 if ((!/object/.test(typeof report)) || (report.hasOwnProperty('code')))
#133        return cb(new Error(report));

to something like:
if ((!/object/.test(typeof report)) || (report.hasOwnProperty('code') || (!Array.isArray(report))))
        return cb(new Error(report));

I will let the author decide the final solution.

**Comment by jas-** [comment]
Pull requests are welcome. Just review the 'contributing' document for details on how to create and submit one.

Thanks for submitting this

**Comment by jas-** [comment]
This has been addressed, thanks for reporting this issue.
