### ISSUE TITLE
Error: Callback was already called (again again).

### ISSUE THREAD

**Issue by charlesfracchia** [jas-/node-libnmap#41]
Hi, I'm having this error as well.
I'm running `node v4.5.0`. Here's the result of the `npm test`.
I can run the examples fine.

```
nmap
    discovery method
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (240ms)
      ✓ unspecified range

  nmap
    scan method
      ✓ default (2024ms)
      ✓ xml report (1963ms)


  9 passing (4s)
  1 failing

  1) nmap discovery method validate report:
     Uncaught Error: Callback was already called.
      at node_modules/async/dist/async.js:844:36
      at node_modules/async/dist/async.js:3676:17
      at node_modules/async/dist/async.js:339:31
      at Object.reporting.reports (lib/libnmap.js:148:16)
      at Socket.bytesend (lib/libnmap.js:259:32)
      at endReadableNT (_stream_readable.js:921:12)
```

**Comment by jas-** [comment]
Could you enable verbose output for the test(s) that are failing? i.e. `verbose: true`?

**Comment by mitchellpontague** [comment]
Here is my output of same issue using verbose output for the test in question.

```
> libnmap@0.2.33 test /guardian/node_modules/libnmap
> mocha -R spec



  nmap
    discovery method
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.1-16
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.17-32
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.33-48
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.49-64
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.65-80
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.81-96
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.97-112
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.113-128
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.129-144
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.145-160
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.161-176
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.177-192
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.193-208
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.209-224
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.225-240
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.15.241-255
Running: nmap  --host-timeout=120s -oX - -sn -PR -6 fe80::134:b6f:827:4e58/128
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      2) invalid flag options
      ✓ unspecified range

  nmap
    scan method
      ✓ default (1128ms)
      ✓ xml report (1039ms)


  8 passing (6s)
  2 failing

  1) nmap discovery method validate report:
     Uncaught Error: Callback was already called.
      at /guardian/node_modules/async/dist/async.js:837:36
      at /guardian/node_modules/async/dist/async.js:5290:17
      at /guardian/node_modules/async/dist/async.js:339:31
      at Object.reporting.reports (lib/libnmap.js:148:16)
      at Socket.bytesend (lib/libnmap.js:259:32)
      at endReadableNT (_stream_readable.js:913:12)

  2) nmap error handling invalid flag options:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being call                                                                                                                                                             ed in this test.




npm ERR! Test failed.  See above for more details.
```

**Comment by charlesfracchia** [comment]
Sorry for the delay, I'm confirming the results @mitchellpontague reports above. With a *slight* difference on the way the invalid flag options are reported.

```
> libnmap@0.2.33 test /Users/charlesfracchia/Downloads/node-libnmap
> mocha -R spec



  nmap
    discovery method
Running: nmap  --host-timeout=120s -oX - -sn -PR -6 fe80::62f8:1dff:fecc:4348/128
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.1-16
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.17-32
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.33-48
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.49-64
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.65-80
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.81-96
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.97-112
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.113-128
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.129-144
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.145-160
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.161-176
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.177-192
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.193-208
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.209-224
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.225-240
Running: nmap  --host-timeout=120s -oX - -sn -PR 192.168.1.241-255
Running: nmap  --host-timeout=120s -oX - -sn -PR -6 fe80::d027:b7ff:fe01:2553/128
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (269ms)
      ✓ unspecified range

  nmap
    scan method
      ✓ default (1857ms)
      ✓ xml report (1837ms)


  9 passing (4s)
  1 failing

  1) nmap discovery method validate report:
     Uncaught Error: Callback was already called.
      at node_modules/async/dist/async.js:844:36
      at node_modules/async/dist/async.js:3676:17
      at node_modules/async/dist/async.js:339:31
      at Object.reporting.reports (lib/libnmap.js:148:16)
      at Socket.bytesend (lib/libnmap.js:259:32)
      at endReadableNT (_stream_readable.js:921:12)



npm ERR! Test failed.  See above for more details.
```

**Comment by jas-** [comment]
Hmm. I am not able to recreate on this end. Could either of you try the `discover.js` example in the [examples](https://github.com/jas-/node-libnmap/tree/master/examples) folder? Also please provide the `node` version installed.

**Comment by jas-** [comment]
@charlesfracchia @mitchellpontague, this should be resolved as of `v0.3.0` available on `npm`. Please confirm.

**Comment by charlesfracchia** [comment]
Hmm
```
<user> @ <path>/node_modules/libnmap:$ npm test

> libnmap@0.3.4 test <path>/node_modules/libnmap
> mocha -R spec



  nmap
    discovery method
      ✓ validate report (100ms)
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (258ms)
      ✓ unspecified range

  nmap
    scan method
      ✓ default (2002ms)
      ✓ xml report (1824ms)


  10 passing (4s)
  1 failing

  1) nmap discovery method validate report:
     Error: done() called multiple times
      at Suite.<anonymous> (test/discover.js:19:5)
      at Suite.<anonymous> (test/discover.js:15:3)
      at Object.<anonymous> (test/discover.js:14:1)
      at require (internal/module.js:12:17)
      at Array.forEach (native)
      at node.js:974:3



npm ERR! Test failed.  See above for more details.
```

**Comment by jas-** [comment]
@charlesfracchia Could you please provide some debugging information (as previously [mentioned](https://github.com/jas-/node-libnmap/issues/41#issuecomment-244376451)) in the test case & possibly show the output of the [discover.js](https://github.com/jas-/node-libnmap/blob/master/examples/discover.js) included example?

**Comment by charlesfracchia** [comment]
Yep, sorry, here the missing section.

```
nmap
    discovery method
Running: nmap  --host-timeout=120s -n -oX - -sn -PR -6 fe80::c2e:8b0e:2414:e44a/128
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.1-16
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.17-32
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.33-48
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.49-64
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.65-80
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.81-96
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.97-112
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.113-128
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.129-144
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.145-160
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.161-176
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.177-192
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.193-208
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.209-224
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.225-240
Running: nmap  --host-timeout=120s -n -oX - -sn -PR 192.168.1.241-255
Running: nmap  --host-timeout=120s -n -oX - -sn -PR -6 fe80::1899:a2ff:fe1a:362d/128
Running: nmap  --host-timeout=120s -n -oX - -sn -PR -6 fe80::dab6:ed3e:f45a:5649/128
      ✓ validate report (103ms)
      1) validate report

```

**Comment by charlesfracchia** [comment]
That test case seems to actually be using `Node v0.10.48` ?
https://travis-ci.org/jas-/node-libnmap/jobs/177298394#L153

**Comment by jas-** [comment]
That is the default version for automated test cases.

Look in the log and you will find the following 

Now using node v4.6.2 (npm v2.15.11)

Because I needed my test harness to examine multiple OS's I had to manually change the node version; see line 328 in the log.  The previous comment link doesn't expand the log when viewed on mobile devices

**Comment by charlesfracchia** [comment]
Hmm, ok. How can I help debug this?
I've noticed that when I do the test, my terminal doesn't show the active line after failing the test. The terminal is still active, but nothing displays. e.g.: up arrow doesn't show the previous command run, despite loading it (if I press <enter>, it will work).
Unlikely to be directly related to the test failing, but thought I would note it

**Comment by charlesfracchia** [comment]
Exact same error comes up with `Node v7.1.0`

**Comment by jas-** [comment]
Ok not the version. Can you provide your available network interfaces and their assigned address & subnet? I.e console.log(require('os').networkInterfaces()

**Comment by charlesfracchia** [comment]
```
> console.log(require('os').networkInterfaces())
{ lo0: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true },
     { address: 'fe80::1',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 1,
       internal: true } ],
  en0: 
   [ { address: 'fe80::46d:ee62:9697:b5c3',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '<redacted>',
       scopeid: 4,
       internal: false },
     { address: '192.168.1.20',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: '<redacted>',
       internal: false } ],
  awdl0: 
   [ { address: 'fe80::182f:7cff:fea9:3592',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '<redacted>',
       scopeid: 9,
       internal: false } ],
  utun0: 
   [ { address: 'fe80::2330:ce4e:dc42:97b7',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 10,
       internal: false } ] }
```

**Comment by jas-** [comment]
@charlesfracchia Strange, the output you mention [here](https://github.com/jas-/node-libnmap/issues/41#issuecomment-262066218); doesn't seem to correspond to the output from the configured IPv6 interfaces.

Can you run the `node examples/ipv6.js` file & the `node examples/discovery.js` file?

**Comment by JonSilver** [comment]
Just an observation... it could be a red herring in this case, but... any unhandled error within the .scan() callback function will result in a spurious "callback was already called" error in async.js.

So, try putting all processing code inside a try/catch block and you may find the error magically disappears. Then you can investigate further.

**Comment by jas-** [comment]
I am going to need more information as I am not going to be able to recreate your issue.

Are you using a fuzzer of some type? Perhaps sending signals to the underlying nmap child processes?

Can you provide the test code you are using and the returned stack? Perhaps enable verbose and report back?

**Comment by jas-** [comment]
@charlesfracchia Is this still an issue? I have a limited testing environment with regards to a full functioning IPv6 network which could be the issue. Any additional information you can provide to help resolve the issue is appreciated.

**Comment by ZackMattor** [comment]
I'm currently hitting this... using flags `-sS` and the range being a single ipaddress. Any idea on how I can help debug?

**Comment by ZackMattor** [comment]
When I hit this error both of these lines get hit.

https://github.com/jas-/node-libnmap/blob/master/lib/libnmap.js#L146-L149

It seems that the correct callback gets called, but within that callback we hit this error `[TypeError: Cannot read property 'map' of undefined]` so then it calls the `cb` in the `catch`...

I'm not sure what is being passed to that method that is causing this error...

**Comment by ZackMattor** [comment]
Found it! If there is any kind of error in the callback in `nmap.scan` it triggers this... and this was only happening for me in a very certain case.

**Comment by latifs** [comment]
Hey @JonSilver,
Can you have an example of try...catch block that fixed it?
Thanks

**Comment by latifs** [comment]
Hey guys just ran the tests and this is what I get:

nmap
    discovery method
      ✓ validate report (208ms)
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (288ms)
      ✓ unspecified range

  nmap
    scan method
      ✓ default (1667ms)
      ✓ xml report (1443ms)


  10 passing (4s)
  1 failing

  1) nmap discovery method validate report:
     Error: done() called multiple times
      at Suite.<anonymous> (test/discover.js:19:5)
      at Suite.<anonymous> (test/discover.js:15:3)
      at Object.<anonymous> (test/discover.js:14:1)
      at require (internal/module.js:11:18)
      at Array.forEach (native)
      at startup (bootstrap_node.js:158:16)
      at bootstrap_node.js:575:3

Could this be related to "Callback was already called"

**Comment by jas-** [comment]
@latifs could you provide output from 'console.log(require('os').networkInterfaces())'?

**Comment by jas-** [comment]
@charlesfracchia, @latifs, @JonSilver, @ZackMattor; I am closing this issue as `legacy` due to the minor version updates and lack of activity on this issue.

If you update and encounter the same issue please create a new issue and report the following information so I can address it more accurately;

1. The versions; node, npm, os etc.
2. The libnmap version
3. The method being used; i.e. discovery and/or scan
4. The output of `console.log(require('os').networkInterfaces())`
5. The output of `npm test`
6. The test case code you are using so I can accurately try to recreate the issue

I do appreciate you all chiming in on this issue but where I am unable to recreate & the current version iteration I am marking this as closed. Thanks.
