### ISSUE TITLE
hasbin

### ISSUE THREAD

**Issue by xllab** [jas-/node-libnmap#43]
in line 547 hasbin.sync on libnmap.js is throwing error for external compiled nmap binary (i can successfully use when i disabled check). can you change?

**Comment by jas-** [comment]
No, not without additional information.

Please provide your use case which causes the error, the operating system and versioning of node, libnmap etc.

Thanks

**Comment by xllab** [comment]
You can try any operating system jas (with compile latest version of nmap). its your project. besides "callback already called" error annoying me too. i think there is an logical issue.

but beyond the errors thanks for your time :)

**Comment by jas-** [comment]
So you are saying the build and tests are incorrect?

[v0.3.8](https://travis-ci.org/jas-/node-libnmap)

You will have to elaborate and provide more information then that for me to proceed.

**Comment by jas-** [comment]
@xllab I have not seen a test case to illustrate your issue. Is this still a problem?

**Comment by jas-** [comment]
@xllab I am closing this issue due to lack of information regarding a use case. If are still experiencing issues and you can provide a use case don't hesitate to open a new issue.
