### ISSUE TITLE
TypeError about IPV6

### ISSUE THREAD

**Issue by lluiscab** [jas-/node-libnmap#44]
`Uncaught Exception:
TypeError: v6.Address is not a constructor
    at Object.command (.../node_modules/node-libnmap/lib/node-libnmap.js:253:16)
`

**Comment by jas-** [comment]
No certain about the version or installation method you are using but v0.3.9 is the latest and can be installed with 'npm install libnmap'

**Comment by lluiscab** [comment]
Okay I've updated the module but now I'm getting this :S 
`Uncaught Exception:
TypeError: Cannot read property 'split' of undefined
    at Address6.parse4in6 (.../node_modules/ip-address/lib/ipv6.js:537:23)
    at Address6.parse (.../node_modules/ip-address/lib/ipv6.js:569:18)
    at new Address6 (.../node_modules/ip-address/lib/ipv6.js:92:29)
    at Object.command( .../node_modules/libnmap/lib/libnmap.js:280:16)
    at block (.../node_modules/libnmap/lib/libnmap.js:240:23)
`

**Comment by jas-** [comment]
Are you following the documentation? Do you actually have some network configuration on any installed interfaces? Have you examined the examples for usage?

I need more to go on to assist you. Please provide details of OS, network config and code examples

**Comment by lluiscab** [comment]
`scanner.scan({ range: ['192.168.1.0/24'], ports: 8 }, function(err, report) {
				
				if (err) console.error(err);
				
				report.forEach(function(item){
					console.log(item[0]);
				});
				
			});`

Ubuntu 16.04, Using IPs of class C (192.168.1.0) and a network mask of 24

**Comment by jas-** [comment]
Your original description speaks specifically of IPv6 and yet you only describe the IPv4 CIDR range of your NAT.

Have you tried the ports example provided [here](https://github.com/jas-/node-libnmap/blob/master/examples/ports.js)

**Comment by jas-** [comment]
@lluiscab Are you still experiencing issues?

**Comment by lluiscab** [comment]
It actually fixed itself for some reason... ;)

**Comment by jas-** [comment]
Good to hear, thanks for reporting it
