### ISSUE TITLE
Can I get the OS version?

### ISSUE THREAD

**Issue by qq351844** [jas-/node-libnmap#45]
I want to use the nmap to detect the Class C IP.
But I want to get the OS version of host.
This lib can get the OS information?

Thank you for your help~

**Comment by jas-** [comment]
Have you read the accompanying README documentation? While cliche it would have provided you with the [following](https://gist.github.com/jas-/eae6b0c6e82a4e072b97#file-flags-js) example. The documentation covers the majority of use cases and options available.

**Comment by qq351844** [comment]
thx for your remind.
I could do it successful.
