### ISSUE TITLE
Is it possible to discover network topology which including subnet work ?

### ISSUE THREAD

**Issue by lonelywolf4git** [jas-/node-libnmap#46]
Hi:
I want to do the large network topology discovery, which includes routers,switches(L2/L3).I also want to know their connect relationship, for example , switch connect to router, router connect to switch ,and so on,thanks for your response

**Comment by jas-** [comment]
So an OS fingerprinting scan would provide the OS leading to the possible device type. Most switches and routers would range between a .1, .29, .254 address for IPv4 and would run an embedded OS such as ios for Cisco devices.

With regards to providing their relationships you could make use of the 'flags' option and provide the nmap tracerpute option to give you the hops which in turn gives you the desired relationship.

Hope that helps as what you are asking for is outside the current functionality of the map tool

**Comment by jas-** [comment]
@lonelywolf4git well learned something new.

Looks like there is and NSE script that performs [the geoip lookup](https://nmap.org/nsedoc/scripts/traceroute-geolocation.html) when using the traceroute flag.

Use case;

```
var opts = {
  flags: [
    "--traceroute",
    "--script traceroute-geolocation"
  ]
}
```
