### ISSUE TITLE
hasbin and windows global path

### ISSUE THREAD

**Issue by HarryBurns** [jas-/node-libnmap#49]
hasbin is unable to resolve global windows paths like "C:/Program Files (x86)/Nmap/nmap".

Why do you use glitchy hasbin package instead of https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback or something like that?

Could you fix it, please?

**Comment by jas-** [comment]
Are you proposing a patch or solution or just want to move from a `synchronous` to `async` file system call?

**Comment by HarryBurns** [comment]
I just want to use global windows path like "C:/Program Files (x86)/Nmap/nmap.exe" in `nmap` config param.

```
const opts = {
    nmap: "C:/Program Files (x86)/Nmap/nmap.exe",
    range: [
        '192.168.0.0/24'
    ]
};
```

**Comment by jas-** [comment]
Sounds like a big with the `hasbin` library

**Comment by jas-** [comment]
@HarryBurns I have applied a fix in `v0.4.8` to check the absolute path if the `process.env.PATH`.

**Comment by jas-** [comment]
@HarryBurns Any update or confirmation of resolution?

**Comment by HarryBurns** [comment]
@jas- Oops, sorry, missed your message.

Just checked - everything works fine, except one note - it does not understand spaces in the path. So I just added quotes to the `nmap` option.
``` javascript
const opts = {
    nmap: "\"C:/Program Files (x86)/Nmap/nmap.exe\"",
    range: [
        '192.168.0.0/24'
    ]
};
```
I believe you can wrap the path automatically? Anyway, everything works fine now on Windows. Can't check on Linux or Mac.

**Comment by jas-** [comment]
Have you tried single quotes & double quotes?

**Comment by HarryBurns** [comment]
Only double quotes. I believe single quotes will not work on windows machines. Can't tell about Linux or Mac.

**Comment by jas-** [comment]
@HarryBurns I don't have a Windows system available. Can you try the following example?

```
const opts = {
    nmap: '"C:/Program Files (x86)/Nmap/nmap.exe"',
    range: [
        '192.168.0.0/24'
    ]
};
```

**Comment by HarryBurns** [comment]
@jas- yeah, it works

**Comment by jas-** [comment]
Awesome, closing it out.
