### ISSUE TITLE
Can't use node-libnmap

### ISSUE THREAD

**Issue by Gank** [jas-/node-libnmap#5]
Using NodeJS v0.10.33 I'm getting problems running node-libnmap.

After installing using,
```
npm install node-libnmap
node-libnmap@0.1.12 node_modules/node-libnmap
├── netmask@1.0.4
├── async@0.2.10
└── ipv6@3.1.1 (sprintf@0.1.5, cliff@0.1.10, cli@0.4.5)
```

And running this code,
```
console.log(require('libnmap').nmap())
```

I get,
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'libnmap'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/node_nmap.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Changing it to code to
```
console.log(require('node-libnmap').nmap())
```

I runs but i get the following output:
```
{ name: 'node-libnmap',
  version: 'v0.1.12',
  usage: 'https://github.com/jas-/node-libnmap',
  license: 'https://github.com/jas-/node-libnmap/blob/master/LICENSE',
  issues: 'https://github.com/jas-/node-libnmap/issues',
  nmap: { legal: 'http://nmap.org/book/man-legal.html' } }

/root/node_modules/node-libnmap/lib/node-libnmap.js:192
          throw new Error('The nmap binary was not found. Install nmap');
                ^
Error: The nmap binary was not found. Install nmap
    at /root/node_modules/node-libnmap/lib/node-libnmap.js:192:17
    at Object.cb [as oncomplete] (fs.js:168:19)
```

I installed nmap
```
nmap --version

Nmap version 6.47 ( http://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.2.3 nmap-libpcre-7.6 libpcap-1.6.2 nmap-libdnet-1.12 ipv6
Compiled without: openssl
Available nsock engines: epoll poll select
```

**Comment by cescofry** [comment]
`libnmap` will search for your `/usr/bin` path to see if nap is installed. Try to run `find / -name nmap` and see where your installation is. 
Hint: if you are installing on Mac OS X it will probably be `/usr/local/bin/nmap`
That said I don't know if is an issue that libnmap wants to resolve.

**Comment by jas-** [comment]
@Gank, @cescofry's answer should have resolved this. Can you update the status of this?

**Comment by Galdooo** [comment]
I have similar problem like @Gank, but @cescofry 's answer didn't resolved it. I'm using nmap - 6.47 under Windows 8.1 and here is the output error
E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192
          throw new Error('The nmap binary was not found. Install nmap');
                ^
Error: The nmap binary was not found. Install nmap
    at E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192:17
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)

**Comment by jas-** [comment]
@Galdooo this issue was closed. Open a new issue.
