### ISSUE TITLE
terminal can't echo correctly after scan.

### ISSUE THREAD

**Issue by leochan007** [jas-/node-libnmap#50]
var nmap = require('libnmap')
  , opts = {
      range: [
        '192.168.10.170',
        '192.168.10.175',
        '192.168.10.176'
      ]
    };

nmap.scan(opts, function(err, report) {
  if (err) throw new Error(err);

  for (var item in report) {
    console.log(JSON.stringify(report[item]));
  }
  console.log("before process.exit()");
  process.exit();
});

after scan, terminal can't echo correctly. it can't show the character i type anymore.

**Comment by jas-** [comment]
How many nodes are you scanning? A class A network? What terminal are you using? What kind of buffer does the terminal use? I am going to need additional details to assist

**Comment by leochan007** [comment]
ubuntu 16.04 terminal.   

one host(192.168.10.170) is OK.  if more than 2 hosts or a host range( 192.168.10.170/24) , it shows wrong.

**Comment by jas-** [comment]
It shows wrong?

Now I am confused, your first issue says you cannot use the terminal after the stdout scam results and now you are hinting at wrong results from the scan.

Can you please provide the use case, I.e. actual code used and the output? Keep in mind there are plenty of examples in the accompanying examples folder.

Those examples do not use the `process.exit()` call within the callback function so i am not sure why you are doing that.

**Comment by leochan007** [comment]
var nmap = require('libnmap')
  , opts = {
      range: [
        '192.168.10.170/24',
        '127.0.0.1'
      ]
    };

// tips: 192.168.10.x  is the host range, replace it in your env.

nmap.scan(opts, function(err, report) {

  if (err) throw new Error(err);

  for (var item in report) {
    console.log(JSON.stringify(report[item], null, 2));
  }
});

**Comment by leochan007** [comment]
the bottom line shows wrong. the terminal can't echo any characters i type after exec node [filename].js which include the code above.

![screenshot from 2017-11-29 09-32-02](https://user-images.githubusercontent.com/1071537/33353635-b1ab62b6-d4e9-11e7-9c89-0d9f5ea32398.png)

**Comment by jas-** [comment]
@leochan007 I am unable to recreate the issue.

Can you drop to a node shell and try?

Example:

```javascript
$ node
> var nmap = require('./index.js');
> var opts = { range: ['scanme.nmap.org', '192.168.0.0/26'] };
> nmap.scan(opts, function(err, report) {
..>  if (err) throw new Error(err);

..>  for (var item in report) {
....>    console.log(JSON.stringify(report[item], null, 2));
..>  }
> });
```

I just tested it a few different ways and am unable to recreate your problem.

**Comment by jas-** [comment]
@leochan007 Any additional details?

**Comment by jas-** [comment]
I am going to have to close this out as I cannot recreate the issue and have yet to hear back about the problem.
