### ISSUE TITLE
opts.flags.push is not a function

### ISSUE THREAD

**Issue by codereach-asm** [jas-/node-libnmap#52]
{ range: [ '1.2.3.4' ], ports: '1-65535', flags: ' --open ' }

TypeError: opts.flags.push is not a function
    at Object.init (/usr/src/app/node_modules/libnmap/lib/libnmap.js:97:20)
    at nmap.scan (/usr/src/app/node_modules/libnmap/lib/libnmap.js:680:12)
    at Promise (/usr/src/app/nmap-port-scan.js:116:11)
    at Promise (<anonymous>)
    at doOneScan (/usr/src/app/nmap-port-scan.js:107:9)
    at Promise (/usr/src/app/nmap-port-scan.js:92:19)
    at Promise (<anonymous>)
    at doScans (/usr/src/app/nmap-port-scan.js:84:9)
    at Promise (/usr/src/app/nmap-port-scan.js:38:3)
    at Promise (<anonymous>)

**Comment by jas-** [comment]
@codereach-asm Not sure what you are asking or even saying.

**Comment by codereach-asm** [comment]
Sorry - just got frustrated that the attempt to add a flag to the options object didn't seem to work.

Please ignore and close if this is expected functionality

**Comment by jas-** [comment]
Asking for assistance requires more information than you provide. A use case, the version you are using of the libnmap module, the version of nodejs, your operating system or even results of the bundles examples might help. There is a good checklist of things that make [asking questions](https://hbr.org/2009/05/real-leaders-ask.html) easier for all parties involved.

**Comment by codereach-asm** [comment]
Thanks. I'll check the link. Closing issue now.

**Comment by jas-** [comment]
The link provides information on how to ask questions.

The amount of I formation you provided does not help me help you to determine the problem.

Generally when someone has an issue a description and sometimes a sample of code along with the error allows for me to recreate the problem to determine if it is a bug or something else.

I have reopened the issue in hopes you could provide the code you wrote that triggers the error.

**Comment by jas-** [comment]
You are using a string vs an array as the `flags` option.

Perhaps you should try;

`range: [ '1.2.3.4' ], ports: '1-65535', flags: ['--open'] }`
