### ISSUE TITLE
unable to add flag with spaces

### ISSUE THREAD

**Issue by eladhk** [jas-/node-libnmap#59]
hi
I can't add a flag with space
my example:
`  flags: [
        '-sV',
        '-Pn',
        '--script http-headers',
        '--script-args http.useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"'
]`

this will create a shell nmap command:
`nmap --host-timeout=900s -sV -Pn --script http-headers --script-args http.useragent=\\\"Mozilla/5.0 -oX - -p80  (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36\\\" 127.0.0.1`
in this commad all words after **Mozilla/5.0** jump after **-p80**

the right command is:
`nmap --host-timeout=900s -sV -Pn --script http-headers --script-args http.useragent=\\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36\\\" -oX - -p80 127.0.0.1`

I think it because of child_process.spawn args (if I adding **shell: true** to spawn options this problem fixed)

do you know how to fix this problem?

**Comment by jas-** [comment]
That may be the only solution from what I am finding.

**Comment by jas-** [comment]
@eladhk Have you tried adjusting your `flags` to something like the following?

```javascript
flags: [
  "-sV",
  "-Pn",
  "--script http-headers",
  "--script-args http.useragent=\"Mozilla blah blah\"",
]
```
