### ISSUE TITLE
Documentation error: timeout option is in seconds, not minutes

### ISSUE THREAD

**Issue by weiyin** [jas-/node-libnmap#61]
The timeout option is used like this:

--host-timeout=${opts.timeout}s

The units are seconds, not minutes.

**Comment by jas-** [comment]
Thanks. So like this [example](https://github.com/jas-/node-libnmap/blob/master/examples/timeout.js)?

**Comment by weiyin** [comment]
The example is good, the problem is on the README.md where it says:

timeout {Number} Number of **minutes** to wait for host/port response

**Comment by jas-** [comment]
Thanks, this just landed.
