### ISSUE TITLE
The nmap binary was not found. Install nmap

### ISSUE THREAD

**Issue by Galdooo** [jas-/node-libnmap#8]
I'm using Nodejs v0.12.0 and nmap v6.47 under windows 8.1.
If I write in command prompt "nmap -sn /some IP/" everything work, but when I use node-libnmap throw me error:
<pre><code>
require('node-libnmap').nmap('discover', function(err, report){
    if (err) throw err
    console.log(report)
})
</code></pre>
and here is the error:
<pre><code>
E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192
          throw new Error('The nmap binary was not found. Install nmap');
                ^
Error: The nmap binary was not found. Install nmap
    at E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192:17
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)
</code></pre>

**Comment by Galdooo** [comment]
and I have this error when I use opts with directory of the nmap

<code>
                   ^
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Program Files (x86)
\Nmap -oG - -sn 192.168.0.193-223"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
</code>

**Comment by jas-** [comment]
@Galdooo Can you provide a test case for the last post? (And thank you for creating a new issue).

I am not a windows guy but I believe the following should work:

```javascript
var opts = {
  nmap: "\Program Files (x86)\Nmap\nmap"
  /* options */
}

require('node-libnmap').nmap('scan', opts, function(err, report){
    if (err) throw err;
    console.log(report);
});```

**Comment by Galdooo** [comment]
I tried this but without success it trow me error:
<code>
E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192
          throw new Error('The nmap binary was not found. Install nmap');
                ^
Error: The nmap binary was not found. Install nmap
    at E:\base\node_modules\node-libnmap\lib\node-libnmap.js:192:17
    at FSReqWrap.cb [as oncomplete] (fs.js:228:19)
</code>
and when I tried the test from the last post it gave me 
<code>
 ^ Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Program Files (x86) \Nmap -oG - -sn 192.168.0.193-223" 'C:\Program' is not recognized as an internal or external command, operable program or batch file.
</code>

**Comment by jas-** [comment]
@Galdooo I could really use a complete test case. A sample of the code you are using is beneficial vs. simply looking at the errors.

If the example below does not work then you may need to use a more verbose method of specifying the `nmap` binary. (See immediately following this example).

```javascript
var lib = require('node-libnmap')
  , opts = {
      nmap: "\Program Files (x86)\Nmap\nmap"
      /* additional options */
    };

lib.nmap('discover', opts, function(err, report){
  if (err) throw err;
  console.log(report);
});
```

If the above example still isn't working then you may want to specify the options like so:

```javascript
opts = {
  nmap: '\WINDOWS\system32\cmd.exe /s /c "C:\Program Files (x86) \Nmap\nmap"'
};
```

As I said I am not a windows guy but the error your seeing indicates that the nmap tool in windows is executed from a shell (cmd.exe prompt) which the last example here specifies the full path within the `%WINDOWS% %SYSTEM32%` directory with the `/c` switch for 'command'. You can brush up on `cmd.exe` by running `cmd /?`

**Comment by Galdooo** [comment]
It still give me <code>Error: The nmap binary was not found.</code>
but I found another solution without this nmap package
<code>
childProcess = require('child_process').spawn('C:\\Program Files (x86)\\Nmap\\nmap.exe',
				[here we write code which we want to execute ]);</code>
<code>childProcess.stdout.on('data', function (data) {
				console.log(data);
});
</code>

This is another technique to work with nmap over nodejs

**Comment by jas-** [comment]
@Galdooo, wow. You are a genius! Glad it is working for you.
